### ISSUE TITLE
A question about temperature module

### ISSUE THREAD

**Issue by ethanluoyc** [ikostrikov/jaxrl#17]
Hi, 

Thanks a lot for the great implementation!

I have a question regarding the temperature, I saw that in 
https://github.com/ikostrikov/jax-rl/blob/main/jax_rl/agents/sac/temperature.py#L16

You are computing the temperature (entropy coefficient) by this instead of directly taking an exp on the log-temperature. Is there a particular reason that you implement it this way as compared to other implementation (for example, the pytorch DrQ, soft learning etc.)

Thanks!

**Comment by ikostrikov** [comment]
Hi Luo,

It's implemented exactly the same way as in pytorch sac/drq and soft learning. It might look different due to slightly different syntax of flax/jax, it's implemented as a module to handle the internal state and the optimizer easier (via the Model class).

**Comment by ethanluoyc** [comment]
Hmm Interesting. I must have misunderstood something. Let me take another look!

**Comment by ethanluoyc** [comment]
So I took a look at this more closely, yeah it makes sense to me by thinking of this as a re-parameterization. I think it can be more obvious to define a constant initializer as 
```
lambda key, shape, dtype: jnp.ones(shape, dtype) * jnp.log(initial_temperature)
```
but this is just a cosmetic change.  
Thanks again for the clarification!

Another thing unrelated to this. I have noticed that you are using orthogonal initialization throughout in DrQ except for the linear layer here https://github.com/ikostrikov/jax-rl/blob/main/jax_rl/agents/drq/networks.py#L67. 
This is intentional as it will have a performance difference? I also noticed that you set the scale of orthogonal initialization to be jnp.sqrt(2) for all of the linear and conv layers including the layers not followed by a relu (if I understand correctly, you would normally use a sqrt 2 scale for layers followed by relu but 1 elsewhere), I am just wondering if this is intentional. I am fairly new to SAC am wondering how these implementation details may affect performance.

**Comment by ikostrikov** [comment]
Thanks! I will add this initialization to avoid any further confusion:)

It's a mistake, the dense layers before tanh were supposed to be initialized the same way as the other layers. Thanks for catching it! I will re-run it and fix the init here. Probably, it was not that important how to initialize this layer due to layer norm but I will change it for consistency anyway.

Yes, the linear layers should be initialized with scaling equal to 1 instead of sqrt(2) but since it's just a single layer in the end of the neural net, it doesn't not effect training significantly. Personally, I simply always use sqrt(2) because relu layers dominate over other layers.

**Comment by ikostrikov** [comment]
Temperature initialization is fixed in https://github.com/ikostrikov/jax-rl/commit/5e044e1fd080223ef5e71848b9d0f72597f2ab2f

**Comment by ethanluoyc** [comment]
Thanks a lot! If you can share the ablation with the initialization that would be awesome!

**Comment by ikostrikov** [comment]
The results seem to be slightly worse after change the init:

![results_drq (1)](https://user-images.githubusercontent.com/1212494/117064957-d32ef600-acf4-11eb-83d3-2567e5af5d74.png)

I'm going to keep the initialization without changing for now. Also it's possible that I didn't run enough seeds (I ran only 10) and will 20 the results will be identical.

**Comment by ethanluoyc** [comment]
That seems interesting. I also suspect that running with more seeds would produce identical results. Are you using scale of 1.0 or sqrt 2?

________________________________

**Comment by ikostrikov** [comment]
I used sqrt 2.0
